function prev = warnings(state)
% WARNINGS Suppress or restore all processFNIRS2 warnings
%
% Toggles all pf2-prefixed warnings on or off. Useful for batch
% processing scripts where informational messages (ROI channel removal,
% default DPF age, baseline validation) create excessive output.
%
% Syntax:
%   pf2.settings.warnings('off')    % Suppress all pf2 warnings
%   pf2.settings.warnings('on')     % Restore all pf2 warnings
%   prev = pf2.settings.warnings('off')  % Returns previous states
%   pf2.settings.warnings(prev)     % Restore from saved states
%
% Inputs:
%   state - 'on', 'off', or a struct returned by a previous call
%           (to restore exact previous states)
%
% Outputs:
%   prev - (optional) Struct of previous warning states, pass back to
%          restore original settings
%
% Example:
%   % Silence warnings during batch processing
%   prev = pf2.settings.warnings('off');
%   for i = 1:numel(allData)
%       allData{i} = processFNIRS2(allData{i});
%   end
%   pf2.settings.warnings(prev);  % Restore
%
%   % Or just turn off permanently for a session
%   pf2.settings.warnings('off');
%
% See also: pf2.settings.settings, warning

% All pf2-prefixed warning IDs
ids = { ...
    'pf2:buildROI:removedChannels', ...
    'pf2:buildROI:singleChannel', ...
    'pf2:processStageFilterHb:noROIBuildStep', ...
    'pf2:processFNIRS2:noAge', ...
    'pf2:initialize:defaultAge', ...
    'pf2:resample:invalidBaseline', ...
    'pf2:fchMaskMismatch', ...
    'pf2:SCIRejection:nyquist', ...
    'pf2:SCIRejection:sciFailed', ...
    'pf2:bpf_iir:tooShort', ...
    'pf2:wavelab', ...
    'pf2:Pipeline:unknownFunc', ...
    'pf2:NameSanitized', ...
    'pf2:PipelineFunction:contextArg', ...
    'pf2:PipelineFunction:varargin', ...
    'pf2:ssr:noProbe', ...
    'pf2:ssr:noShortChannels', ...
    'pf2:ssr:noLongChannels', ...
    'pf2:ssr:dimMismatch', ...
    'pf2:storeMethodsLib:structContext', ...
    'pf2:UnknownFormat', ...
    'pf2:qc:sci:lowFs', ...
    'pf2:qc:sci:bandClamped', ...
    'pf2:qc:pipeline:noRaw', ...
    'pf2:qc:pipeline:noFs', ...
    'pf2:qc:pipeline:noTime', ...
    'pf2:qc:pipeline:badCheck', ...
    'pf2:qc:takizawa:noHb', ...
    'pf2:qc:takizawa:noTime', ...
    'pf2:probe:transformToMNI:highError', ...
    'pf2:data:importInfo:unusedRows', ...
    'pf2:data:importBlockInfo:unusedRows', ...
    'pf2:TooManyMarkers', ...
    'pf2:importDirectory:allFailed', ...
    'pf2:ReservedArgMismatch', ...
    'pf2:import:unknownChannelCount', ...
    'pf2:initialize:defaultBaseline', ...
    'pf2:plot:tooManyMarkers', ...
    'pf2:resample:emptyAux', ...
    'pf2:import:bidsEventsFailed', ...
    'pf2:import:bidsCoordFailed', ...
    'pf2:stats:lmeFailed', ...
    'pf2:stats:fitInfoNaN', ...
    'pf2:hyperscanning:dyadFailed', ...
    'pf2:probe:transformToMNI:info' ...
};

%% Restore from saved struct
if isstruct(state)
    savedIds = fieldnames(state);
    for i = 1:numel(savedIds)
        warning(state.(savedIds{i}).state, savedIds{i});
    end
    if nargout > 0
        prev = state;
    end
    return;
end

%% Validate
assert(ischar(state) || isstring(state), ...
    'pf2:settings:warnings:badInput', ...
    'Input must be ''on'', ''off'', or a struct from a previous call.');
state = char(state);
assert(ismember(state, {'on', 'off'}), ...
    'pf2:settings:warnings:badState', ...
    'State must be ''on'' or ''off''.');

%% Save previous states and apply
savedStates = struct();
for i = 1:numel(ids)
    id = ids{i};
    safeKey = strrep(strrep(id, ':', '_'), '.', '_');
    [~, savedStates.(safeKey)] = warning('query', id);
    warning(state, id);
end

if nargout > 0
    prev = savedStates;
end

end
