function outputPath = generate(pipeline, basePath, varargin)
% GENERATE Create HTML report from Pipeline results
%
% Generates a self-contained HTML report with embedded CSS, figures as
% linked images, and formatted tables.
%
% Syntax:
%   outputPath = exploreFNIRS.report.generate(pipe, 'output/report')
%   outputPath = exploreFNIRS.report.generate(pipe, 'output/report', ...
%       'SaveFigures', true, 'DPI', 300)
%
% Inputs:
%   pipeline - Pipeline object (after run())
%   basePath - Base path for output (creates basePath.html and basePath_figures/)
%
% Name-Value Parameters:
%   SaveFigures - Save figures as image files (default: true)
%   FigureFormat - 'png' (default), 'svg', 'pdf'
%   DPI         - Figure resolution (default: 300)
%   FigureWidth - Figure width in pixels (default: 800)
%   FigureHeight - Figure height in pixels (default: 500)
%   IncludeLatex - Include LaTeX table code in HTML (default: false)
%
% Outputs:
%   outputPath - Path to generated HTML file
%
% Example:
%   pipe = exploreFNIRS.report.Pipeline(ex);
%   pipe.addStep('lme', 'Biomarkers', {'HbO'});
%   pipe.addStep('temporal', 'Biomarkers', {'HbO'});
%   pipe.run();
%   path = exploreFNIRS.report.generate(pipe, 'results/my_report');
%   web(path);
%
% See also: exploreFNIRS.report.Pipeline, exploreFNIRS.report.toLatex

    ip = inputParser;
    addRequired(ip, 'pipeline');
    addRequired(ip, 'basePath', @ischar);
    addParameter(ip, 'SaveFigures', true, @islogical);
    addParameter(ip, 'FigureFormat', 'png', @ischar);
    addParameter(ip, 'DPI', 300, @isnumeric);
    addParameter(ip, 'FigureWidth', 800, @isnumeric);
    addParameter(ip, 'FigureHeight', 500, @isnumeric);
    addParameter(ip, 'IncludeLatex', false, @islogical);
    parse(ip, pipeline, basePath, varargin{:});
    opts = ip.Results;

    if ~pipeline.isRun
        error('exploreFNIRS:report:generate', ...
            'Pipeline has not been run yet. Call pipe.run() first.');
    end

    % Create output directories
    htmlPath = [basePath, '.html'];
    figDir = [basePath, '_figures'];

    [outDir, ~, ~] = fileparts(basePath);
    if ~isempty(outDir) && ~isfolder(outDir)
        mkdir(outDir);
    end

    % Save figures
    figPaths = struct();
    if opts.SaveFigures
        if ~isfolder(figDir)
            mkdir(figDir);
        end

        figNames = fieldnames(pipeline.figures);
        for i = 1:length(figNames)
            name = figNames{i};
            fig = pipeline.figures.(name);
            if ~isempty(fig) && isvalid(fig)
                % Force white background and light-mode styling
                set(fig, 'Color', 'w');
                sty = pf2_base.plot.PlotStyle.getPublication();
                sty.applyToFigure(fig);
                exploreFNIRS.report.forceWhiteMode(fig);
                figPath = fullfile(figDir, sprintf('%s.%s', name, opts.FigureFormat));
                pf2_base.plot.saveFigure(fig, figPath, ...
                    opts.FigureWidth, opts.FigureHeight, opts.DPI);
                % Store relative path for HTML
                [~, figDirName] = fileparts(figDir);
                figPaths.(name) = fullfile(figDirName, ...
                    sprintf('%s.%s', name, opts.FigureFormat));
            end
        end
    end

    % Build HTML
    html = buildHTML(pipeline, figPaths, opts);

    % Write file
    fid = fopen(htmlPath, 'w', 'n', 'UTF-8');
    if fid == -1
        error('exploreFNIRS:report:generate', 'Cannot write to %s', htmlPath);
    end
    fprintf(fid, '%s', html);
    fclose(fid);

    outputPath = htmlPath;
    fprintf('Report saved: %s\n', outputPath);
end


%% Local helpers

function html = buildHTML(pipeline, figPaths, opts)
    cfg = pipeline.config;
    title = cfg.Title;
    if isempty(title)
        title = 'fNIRS Analysis Report';
    end

    parts = {};
    parts{end+1} = '<!DOCTYPE html>';
    parts{end+1} = '<html lang="en">';
    parts{end+1} = '<head>';
    parts{end+1} = '<meta charset="UTF-8">';
    parts{end+1} = sprintf('<title>%s</title>', title);
    parts{end+1} = getCSS();
    parts{end+1} = '</head>';
    parts{end+1} = '<body>';

    % Header
    parts{end+1} = '<div class="header">';
    parts{end+1} = sprintf('<h1>%s</h1>', title);
    if ~isempty(cfg.Author)
        parts{end+1} = sprintf('<p class="meta">Author: %s</p>', cfg.Author);
    end
    parts{end+1} = sprintf('<p class="meta">Date: %s</p>', cfg.Date);
    parts{end+1} = sprintf('<p class="meta">Generated by exploreFNIRS.report at %s</p>', ...
        datestr(now, 'yyyy-mm-dd HH:MM:SS'));
    parts{end+1} = '</div>';

    % Statistics section
    statNames = fieldnames(pipeline.stats);
    if ~isempty(statNames)
        parts{end+1} = '<h2>Statistical Results</h2>';
        parts{end+1} = '<div class="stats-section">';
        for i = 1:length(statNames)
            parts{end+1} = sprintf('<p><strong>%s:</strong> %s</p>', ...
                strrep(statNames{i}, '_', ' '), pipeline.stats.(statNames{i}));
        end
        parts{end+1} = '</div>';
    end

    % Tables section
    tableNames = fieldnames(pipeline.tables);
    if ~isempty(tableNames)
        parts{end+1} = '<h2>Tables</h2>';
        for i = 1:length(tableNames)
            name = tableNames{i};
            T = pipeline.tables.(name);
            parts{end+1} = sprintf('<h3>%s</h3>', strrep(name, '_', ' '));
            parts{end+1} = tableToHTML(T);

            if opts.IncludeLatex
                latex = exploreFNIRS.report.toLatex(T, 'Environment', 'none');
                parts{end+1} = '<details><summary>LaTeX code</summary>';
                parts{end+1} = sprintf('<pre><code>%s</code></pre>', ...
                    strrep(strrep(latex, '<', '&lt;'), '>', '&gt;'));
                parts{end+1} = '</details>';
            end
        end
    end

    % Figures section
    figNames = fieldnames(figPaths);
    if ~isempty(figNames)
        parts{end+1} = '<h2>Figures</h2>';
        for i = 1:length(figNames)
            name = figNames{i};
            parts{end+1} = sprintf('<div class="figure">');
            parts{end+1} = sprintf('<h3>%s</h3>', strrep(name, '_', ' '));
            parts{end+1} = sprintf('<img src="%s" alt="%s">', ...
                figPaths.(name), name);
            parts{end+1} = '</div>';
        end
    end

    % Pipeline info
    parts{end+1} = '<h2>Pipeline Configuration</h2>';
    parts{end+1} = '<div class="config">';
    parts{end+1} = '<table>';
    parts{end+1} = '<tr><th>Step</th><th>Type</th></tr>';
    for i = 1:length(pipeline.steps)
        step = pipeline.steps{i};
        parts{end+1} = sprintf('<tr><td>%d</td><td>%s</td></tr>', i, step.type);
    end
    parts{end+1} = '</table>';
    parts{end+1} = '</div>';

    parts{end+1} = '</body>';
    parts{end+1} = '</html>';

    html = strjoin(parts, newline);
end


function css = getCSS()
    css = ['<style>' newline ...
        'body { font-family: "Helvetica Neue", Arial, sans-serif; ' ...
        'max-width: 900px; margin: 0 auto; padding: 20px; ' ...
        'color: #333; line-height: 1.6; }' newline ...
        '.header { border-bottom: 2px solid #2c3e50; padding-bottom: 15px; margin-bottom: 30px; }' newline ...
        'h1 { color: #2c3e50; margin-bottom: 5px; }' newline ...
        'h2 { color: #34495e; border-bottom: 1px solid #bdc3c7; padding-bottom: 8px; margin-top: 40px; }' newline ...
        'h3 { color: #7f8c8d; }' newline ...
        '.meta { color: #7f8c8d; margin: 2px 0; }' newline ...
        'table { border-collapse: collapse; width: 100%; margin: 15px 0; font-size: 0.9em; }' newline ...
        'th { background: #ecf0f1; padding: 10px 12px; text-align: left; ' ...
        'border-bottom: 2px solid #bdc3c7; font-weight: 600; }' newline ...
        'td { padding: 8px 12px; border-bottom: 1px solid #ecf0f1; }' newline ...
        'tr:hover { background: #f8f9fa; }' newline ...
        '.stats-section p { margin: 5px 0; }' newline ...
        '.figure { margin: 20px 0; text-align: center; }' newline ...
        '.figure img { max-width: 100%; border: 1px solid #ecf0f1; border-radius: 4px; }' newline ...
        'pre { background: #f8f9fa; padding: 12px; border-radius: 4px; overflow-x: auto; }' newline ...
        'code { font-size: 0.85em; }' newline ...
        'details { margin: 10px 0; }' newline ...
        'summary { cursor: pointer; color: #3498db; }' newline ...
        '.config table { width: auto; }' newline ...
        '</style>'];
end


function html = tableToHTML(T)
    varNames = T.Properties.VariableNames;
    useRowNames = ~isempty(T.Properties.RowNames);

    html = '<table>';

    % Header
    html = [html, '<tr>'];
    if useRowNames
        html = [html, '<th></th>'];
    end
    for c = 1:width(T)
        html = [html, sprintf('<th>%s</th>', varNames{c})]; %#ok<AGROW>
    end
    html = [html, '</tr>'];

    % Rows
    for r = 1:height(T)
        html = [html, '<tr>']; %#ok<AGROW>
        if useRowNames
            html = [html, sprintf('<td><strong>%s</strong></td>', ...
                T.Properties.RowNames{r})]; %#ok<AGROW>
        end
        for c = 1:width(T)
            val = T.(varNames{c})(r);
            if isnumeric(val)
                if isnan(val)
                    cellStr = '-';
                else
                    cellStr = sprintf('%.3f', val);
                end
            elseif isstring(val) || ischar(val)
                cellStr = char(val);
            elseif iscell(val)
                cellStr = char(string(val{1}));
            else
                cellStr = char(string(val));
            end
            html = [html, sprintf('<td>%s</td>', cellStr)]; %#ok<AGROW>
        end
        html = [html, '</tr>']; %#ok<AGROW>
    end

    html = [html, '</table>'];
end
