function recipe = identityRecipeSpike()
%IDENTITYRECIPESPIKE Representative schema tree for identity proof tests.
%
% This is deliberately a Phase-0 fixture, not the frozen Recipe v1 schema. It
% mirrors the shipped OD_TDDR raw pipeline and LPF oxy pipeline without storing
% runtime Pipeline objects or function handles. Stable production function IDs
% and the final Recipe field catalog still require their metadata ADR.

    emptyParameter = struct( ...
        'parameterId', {}, ...
        'valueType', {}, ...
        'unit', {}, ...
        'shape', {}, ...
        'value', {});
    cutoffParameter = struct( ...
        'parameterId', 'freq-cut', ...
        'valueType', 'double', ...
        'unit', 'Hz', ...
        'shape', uint64([1 1]), ...
        'value', 0.1);

    stepTemplate = struct( ...
        'functionId', '', ...
        'functionVersion', uint64(1), ...
        'enabled', true, ...
        'parameters', emptyParameter);
    rawSteps = repmat(stepTemplate, 2, 1);
    rawSteps(1).functionId = 'spike.pf2.raw.intensity-to-od';
    rawSteps(2).functionId = 'spike.pf2.raw.motion-correct-tddr';
    oxySteps = stepTemplate;
    oxySteps.functionId = 'spike.pf2.oxy.low-pass-filter';
    oxySteps.parameters = cutoffParameter;

    scientific = struct();
    scientific.inputContract = struct( ...
        'modality', 'fnirs-cw', ...
        'domain', 'intensity', ...
        'wavelengthsNm', uint16([690 830]), ...
        'signalUnit', 'arbitrary-unit');
    scientific.context = struct( ...
        'dpfPolicy', 'fixed', ...
        'fixedDpf', 5.93, ...
        'baselineStartSeconds', 0.0, ...
        'baselineLengthSeconds', 10.0, ...
        'dirtyBaseline', false, ...
        'processRejectedChannels', false);
    scientific.rawSteps = rawSteps;
    scientific.oxySteps = oxySteps;
    scientific.qcPolicy = struct( ...
        'policyId', 'spike.pf2.qc.channel-threshold', ...
        'enabled', true, ...
        'rejectLevel', 0.0);
    scientific.outputs = struct( ...
        'biomarkers', {{'hbo', 'hbr'}}, ...
        'includeOpticalDensity', true);

    recipe = struct();
    recipe.artifactKind = 'pf2.processing.recipe';
    recipe.schemaVersion = uint64(1);
    recipe.artifactId = 'identity-spike-od-tddr-lpf';
    recipe.displayName = ['OD-TDDR + LPF ' char(hex2dec('03B1'))];
    recipe.scientific = scientific;
    recipe.authoredFrom = struct( ...
        'kind', 'shipped-methods', ...
        'rawName', 'OD_TDDR', ...
        'oxyName', 'LPF');
    recipe.authoringDelta = {'Phase-0 identity fixture'};
    recipe.citations = { ...
        'Fishburn et al. (2019), doi:10.1016/j.neuroimage.2018.09.025'};
end
